# syntax=docker/dockerfile:1.6

#FROM ubuntu:20.04
FROM --platform=$BUILDPLATFORM ubuntu:22.04


ARG DEBIAN_FRONTEND=noninteractive
ARG TARGETARCH

# ------------------------------------------------------
# Base packages
# ------------------------------------------------------
RUN apt-get update && apt-get install -y zlib1g-dev libicu-dev g++
RUN apt-get update \
    && apt-get install -y wget vim telnet git curl \
    && apt update && apt-get install supervisor -y 

RUN apt-get update && apt-get install -y \
    zlib1g-dev \
    libssl-dev \
    libsasl2-dev \
    libzstd-dev \
    git \
    build-essential \
    make

# ------------------------------------------------------
# Filebeat (multi-arch safe)
# ------------------------------------------------------
RUN wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add - \
    && echo "deb https://artifacts.elastic.co/packages/8.x/apt stable main" | tee /etc/apt/sources.list.d/elastic-8.x.list \
    && apt-get update \
    && apt-get install filebeat=8.3.2 \
    && apt-mark hold filebeat \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# ------------------------------------------------------
# PHP 8.0 and modules
# ------------------------------------------------------
RUN apt-get update --fix-missing && apt-get install software-properties-common -y && apt-get install pkg-config rsync -y
RUN apt-get update --fix-missing && apt-add-repository ppa:ondrej/php
RUN apt-get update --fix-missing && apt-get install php8.0 php8.0-cli php8.0-common php8.0-redis vim git -y
RUN apt-get update --fix-missing && apt-get install php8.0-curl php8.0-gd -y
RUN apt-get update --fix-missing && apt-get install php8.0-intl php8.0-mysql php8.0-xml php8.0-mbstring php8.0-fpm -y
RUN apt-get update --fix-missing && apt-get install php8.0-zip libapache2-mod-php8.0 php8.0-mongodb -y
RUN apt-get update --fix-missing && apt-get install php8.0-dev php8.0-imagick php8.0-pgsql librdkafka-dev -y
RUN apt-get install pdftk -y

# ------------------------------------------------------
# Composer (multi-arch independent)
# ------------------------------------------------------
RUN wget https://getcomposer.org/download/2.3.10/composer.phar && \
    mv composer.phar composer && chmod +x composer && mv composer /usr/local/bin/
